# Generated by Django 2.2.16 on 2022-02-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220209_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
