# Generated by Django 2.2.16 on 2022-02-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
    ]
